/*
Copyright (c) 2014 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module exdep;

import std.stdio;
import std.digest.crc;
import std.format;
import std.array;
import std.string;
import std.file;
import std.path;
import std.process;

import cmdopt;

string home(string path)
{
    string homeDir;
    version(Posix)
        homeDir = environment.get("HOME");
    version(Windows)
        homeDir = environment.get("APPDATA").replace("\\", "/");
    return homeDir ~ "/" ~ path;
}

class Exdep
{
    string descriptor;
    string id;

    string vcs;
    string hostname;
    string path;
    
    string subdir = "";
    string location;
    
    string srcDir;
    
    bool useHTTPS = false;

    this(string desc, bool https)
    {
        descriptor = desc;
        useHTTPS = https;
        id = crc32Of(descriptor).crcHexString;
        string name;
        formattedRead(descriptor, "%s:%s:%s", &name, &path, &subdir);
        auto pos = indexOf(name, "@");
        if (pos >= 0)
            formattedRead(name, "%s@%s", &vcs, &hostname);
        else
            vcs = name;

        if (vcs != "local")
            // TODO: use config to override this
            location = home(format(".cook/remote/%s", id));
        else
            location = path;
            
        if (subdir.length)
            srcDir = location ~ "/" ~ subdir;
        else
            srcDir = location;
    }

    void print()
    {
        writefln("id: %s", id);
        writefln("VCS: %s", vcs);
        writefln("Host: %s", hostname);
        writefln("Path: %s", path);
    }

    void fetch(CmdOptions ops)
    {
        if (vcs != "local")
        {
            if (exists() && isDir(location))
            {
                if (ops.rebuild)
                {
                    writefln("Fetching %s (%s from %s)...", id, path, hostname);
                    pull();
                }
            }
            else
            {
                writefln("Fetching %s (%s from %s)...", id, path, hostname);
                clone();
            }
        }
    }

    bool exists()
    {
        return (std.file.exists(location));
    }

    void clone()
    {
        if (vcs == "git")
        {
            string command;
            if (useHTTPS)
                command = format("git clone https://%s/%s.git %s", hostname, path, location);
            else
                command = format("git clone git@%s:%s.git %s", hostname, path, location);
            writeln(command);
            std.process.system(command);
        }
    }

    void pull()
    {
        if (vcs == "git")
        {
            string command = format("cd %s && git pull", location);
            writeln(command);
            std.process.system(command);
        }
    }
}

